config/routes.rb
FiWareIdm::Application.routes.draw do
  # FIWARE compatible routes
  match '/authorize', to: 'authorizations#new'
  post  '/token', to: proc { |env| SocialStream::Oauth2Server::TokenEndpoint.new.call(env) }

  # match '/premium_registration' => "user_registrations#premium_registration"

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', registrations: 'user_registrations'}

  devise_scope :user do
   get "premium_registration", to: "user_registrations#premium_registration"
  end

  namespace :permission do
    resources :customs
  end

  resources :purchases
  resources :roles

  #Role Assignment. REST API
  match '/applications/:app_id/actors' => "applications#index_actors", :via => :get, :format => :json
  match '/applications/:app_id/actors' => "applications#create_actor", :via => :post, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#show_actor", :via => :get, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#update_actor", :via => :put, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#delete_actor", :via => :delete, :format => :json

  #Authentication Token API
  namespace :api do
    namespace :v1  do
      resources :tokens,:only => [:create, :destroy]
    end
  end

  #SCIM 2.0 API
  namespace :v2 do
    resources :users
    resources :organizations
    match '/ServiceProviderConfigs' => "base#getConfig"
    match '/testing' => "base#testing"
  end

  match '/terms-of-service' => 'frontpage#terms_of_service', as: :terms_of_service
end

app/views/frontpage/_external_login.html.erb
<%- if ExternalIdp.count > 0 %>
  <section id="external_sign_in">
    <h3 title="<%= t('idp.frontpage.title') %>">
      <%= t('idp.frontpage.text') %>
    </h3>
    <article class="login_data">

      <%- if devise_mapping.omniauthable? %>
        <%- resource_class.omniauth_providers.each do |provider| 
            info_idp = ExternalIdp.find_by_route(omniauth_authorize_path(resource_name, provider))
            if !info_idp.blank? && info_idp[:enabled] -%>
        <div style="margin: .8em 0 .8em 0">
            <span> <%= if info_idp.logo_url.nil?
                image_path = "/assets/logos/small/site.png"              
              else
                image_path = info_idp.logo_url 
              end 
              link_to image_tag(image_path, :alt => info_idp.description, :title => info_idp.description), omniauth_authorize_path(resource_name, provider)
          %>
            </span><span style="height: 20px; display: inline-block; vertical-align: center;"><%=info_idp.description%></span>
        </div>
          <% end -%>
        <% end -%>
      <% end -%>
    </article>
  </section>
 <% end -%>

app/views/frontpage/_presentation.html.erb
<article id="presentation">
  <script>
    var confirm_help_box = function () {
      var r = confirm("The communications sent to the FIWARE Lab support list are public and they generate public tickets. Please avoid sending private info unless you are happy to see it publicly available.");
      if (r == true) {
          window.location = "mailto:fiware-lab-help@lists.fi-ware.org?Subject=FI-Lab Assistance";
      } 
    }
   </script>
  <section class="media">
    <h3 class="media-heading">
      FIWARE Lab
    </h3>
    <span>
      FIWARE Lab is a working instance of FIWARE available for experimentation.
    </span>
    <p>
      You will be able to setup the basic virtual infrastructure needed to run applications that make use of the APIs provided by FIWARE Generic Enablers deployed as a Service either globally or by you (as private instance).
    </p>
    <div class="sign_up">
      <%= link_to t('devise.links.sign_up'), new_registration_path(resource_name) %>
    </div>
  </section>

   <section class="help-bar">
        <div style="cursor: pointer;" class="help-box" onclick="confirm_help_box()">
            <header>
              <img src="/assets/help.png">
              <h5>Need Help?</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          <div>
            Ask a question.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://catalogue.fi-ware.org/enablers">
            <header>
              <img src="/assets/ges.png">
              <h5>Our GEs</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>  
          <div>
            See our Catalogue.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="https://www.fi-xifi.eu/fi-ops.html">
            <header>
              <img src="/assets/fi-ops.png">
              <h5>FIWARE Lab nodes</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>
          <div>
            Learn about FIWARE Ops.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://edu.fi-ware.org/">
            <header>
              <img src="/assets/more-info.png">
              <h5>eLearning</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>
          <div>
            Train yourself.
          </div>
        </div>
      
      </section>
     
</article>

app/views/frontpage/_presentation_default.html.erb
<article>
<section class="media">
    <h3 class="media-heading">
      FI-Lab
    </h3>
    <span>
      FI-Lab is a working instance of FI-WARE available for experimentation.
    </span>
    <p>
      You will be able to setup the basic virtual infrastructure needed to run applications that make use of the APIs provided by FI-WARE Generic Enablers deployed as a Service either globally or by you (as private instance).
    </p>
    <div class="sign_up">
      <%= link_to t('devise.links.sign_up'), new_registration_path(resource_name) %>
    </div>
  </section>
   <section class="help-bar">
        <div class="help-box">
          <a href="mailto:fiware-lab-help@lists.fi-ware.org?Subject=FI-LAB Assistance">
            <header>
              <img src="assets/help.png">
              <h5>Need Help?</h5>
              <i class="fa fa-chevron-right"></i>
            </header>
          </a>
          <div>
            Ask a question.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://catalogue.fi-ware.org/enablers">
            <header>
              <img src="assets/ges.png">
              <h5>Our GEs</h5>
              <i class="fa fa-chevron-right"></i>
            </header>
          </a>  
          <div>
            See our Catalogue.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="https://www.fi-xifi.eu/fi-ops.html">
            <header>
              <img src="assets/fi-ops.png">
              <h5>FI-Lab nodes</h5>
              <i class="fa fa-chevron-right"></i>
            </header>
          </a>
          <div>
            Learn about FI-Ops.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://edu.fi-ware.org/">
            <header>
              <img src="assets/more-info.png">
              <h5>eLearning</h5>
              <i class="fa fa-chevron-right"></i>
            </header>
          </a>
          <div>
            Train yourself.
          </div>
        </div>
      
      </article>
</section>

app/views/frontpage/terms_of_service.html.erb
<section id="terms_of_service">
  <%= render partial: 'toolbar/terms_of_service'%>
</section>